{
    'name': 'Invoice OCR',
    'version': '19.0.1.0.0',
    'summary': 'Escáner de facturas de proveedor con OCR local, sin API',
    'author': 'Alberto Cantero',
    'website': 'https://github.com/albcantero/invoice_ocr',
    'license': 'LGPL-3',
    'category': 'Accounting',
    'depends': ['account'],
    'external_dependencies': {'python': ['rapidocr_onnxruntime', 'fitz']},
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'views/invoice_ocr_document_views.xml',
        'wizards/invoice_ocr_upload_views.xml',
        'views/invoice_ocr_menus.xml',
        'views/res_config_settings_views.xml',
    ],
    'application': True,
    'installable': True,
}
